name: "Test KiABOM"

on:
  push:

jobs:
  python-test:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create config.yaml
        shell: bash
        run: |
            echo "" > src/config.yaml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
          cache: "pip"
          cache-dependency-path: src/requirements.txt
      - name: Pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Ruff
        run: |
          pip3 install ruff
          ruff format src/kiabom.py
          ruff check src/kiabom.py
          ruff format tests/test_kiabom.py

      - name: Install deps
        run: |
          pip3 install -r src/requirements.txt
          pip3 install pytest pytest-cov

      - name: Test with pytest
        env:
          DISABLE_API: "true"
        run: |
          pytest -vv
