name: "Test KiABOM"

on:
  push:

jobs:
  python-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"
          cache-dependency-path: src/requirements.txt
      - name: Pip
        run: |
          python -m pip install --upgrade pip

      - name: Autoformat
        run: |
          pip install ruff
          ruff format src/kiabom.py
          ruff format tests/test_kiabom.py

      - name: Install deps
        run: |
          pip install -r src/requirements.txt
          pip install setuptools
          pip install six
          pip install pytest pytest-cov

      - name: Test with pytest
        run: |
          pytest -vv
